name: lo que queramos
on:
  push:
    branches: [ "main" ]
jobs:
  platzi:
    runs-on: ubuntu-latest
    steps: 
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: "install dependencies"
        run: npm install
      - name: "run tests"
        run: npm test
