name: Rick and Morty CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  platzi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps: 
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "setup node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: "install dependencies"
        run: npm install --no-audit --no-fund
      - name: "run tests"
        run: npm test
      - name: "run lint"
        run: npm run lint
      - name: "muestra el contenido del directorio"
        run: ls -la
